# Generated by Django 5.2.10 on 2026-01-24 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
        ('workflow', '0010_delete_usgreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(help_text='Section name, e.g., Kidneys', max_length=100)),
                ('name', models.CharField(help_text='Parameter label, e.g., Right Kidney Size', max_length=200)),
                ('parameter_type', models.CharField(choices=[('number', 'Number'), ('dropdown', 'Dropdown'), ('checklist', 'Checklist'), ('boolean', 'Boolean'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('heading', 'Heading'), ('separator', 'Separator')], max_length=20)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement, e.g., mm', max_length=20, null=True)),
                ('normal_value', models.CharField(blank=True, help_text='Default/Normal value', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['profile', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code, e.g., USG_KUB', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human readable name', max_length=150)),
                ('modality', models.CharField(help_text='Modality code, e.g., USG', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameterOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reporting.reportparameter')),
            ],
            options={
                'ordering': ['parameter', 'order'],
            },
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reporting.reportprofile'),
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('service_visit_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_instance', to='workflow.servicevisititem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='reporting.reportprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.reportparameter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reporting.reportinstance')),
            ],
            options={
                'unique_together': {('report', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='ServiceReportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enforce_single_profile', models.BooleanField(default=True, help_text='If user must use this profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='reporting.reportprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_profiles', to='catalog.service')),
            ],
            options={
                'unique_together': {('service', 'profile')},
            },
        ),
    ]
