# Generated by Django 5.2.10 on 2026-02-04 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
        ('workflow', '0012_receiptsnapshot_referring_consultant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBlockLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('block_type', models.CharField(choices=[('ui', 'UI Component'), ('narrative', 'Narrative Snippet')], default='ui', max_length=50)),
                ('content', models.JSONField(help_text='JSON schema/UI schema or narrative rule snippet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(help_text='Section name, e.g., Kidneys', max_length=100)),
                ('name', models.CharField(help_text='Parameter label, e.g., Right Kidney Size', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier within profile', max_length=200, null=True)),
                ('parameter_type', models.CharField(choices=[('number', 'Number'), ('dropdown', 'Dropdown'), ('checklist', 'Checklist'), ('boolean', 'Boolean'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('heading', 'Heading'), ('separator', 'Separator')], max_length=20)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement, e.g., mm', max_length=20, null=True)),
                ('normal_value', models.CharField(blank=True, help_text='Default/Normal value', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('sentence_template', models.TextField(blank=True, help_text='Template like: {name}: {value}{unit}.', null=True)),
                ('narrative_role', models.CharField(choices=[('finding', 'Finding'), ('impression_hint', 'Impression Hint'), ('limitation_hint', 'Limitation Hint'), ('ignore', 'Ignore')], default='finding', max_length=50)),
                ('omit_if_values', models.JSONField(blank=True, help_text="List of values to omit sentence for, e.g. ['na', false]", null=True)),
                ('join_label', models.CharField(blank=True, help_text="Join label for checklists, e.g. 'and'", max_length=50, null=True)),
            ],
            options={
                'ordering': ['profile', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportParameterLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(help_text='e.g. USG, XR, CT', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier, e.g. liver_size', max_length=200, unique=True)),
                ('parameter_type', models.CharField(choices=[('number', 'Number'), ('dropdown', 'Dropdown'), ('checklist', 'Checklist'), ('boolean', 'Boolean'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('heading', 'Heading'), ('separator', 'Separator')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('default_normal_value', models.CharField(blank=True, max_length=500, null=True)),
                ('default_sentence_template', models.TextField(blank=True, null=True)),
                ('default_omit_if_values', models.JSONField(blank=True, null=True)),
                ('default_options_json', models.JSONField(blank=True, help_text='List of {label, value} for dropdowns', null=True)),
                ('default_join_label', models.CharField(blank=True, max_length=50, null=True)),
                ('default_narrative_role', models.CharField(default='finding', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplateV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code, e.g., USG_KUB_V2', max_length=50)),
                ('name', models.CharField(help_text='Human readable name', max_length=150)),
                ('modality', models.CharField(help_text='Modality code, e.g., USG', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('json_schema', models.JSONField(default=dict)),
                ('ui_schema', models.JSONField(default=dict)),
                ('narrative_rules', models.JSONField(blank=True, default=dict, help_text='Narrative generation rules')),
                ('is_frozen', models.BooleanField(default=False, help_text='If true, template cannot be edited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(help_text='Organization Name', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('report_logo', models.ImageField(blank=True, null=True, upload_to='printing/')),
                ('disclaimer_text', models.TextField(blank=True, default='This report is electronically verified.')),
                ('signatories_json', models.JSONField(blank=True, default=list, help_text='List of {name, designation}')),
                ('receipt_header_text', models.CharField(default='Consultant Place Clinic', max_length=200)),
                ('receipt_footer_text', models.TextField(blank=True, default='Adjacent Excel Labs, Near Arman Pan Shop Faisalabad Road Jaranwala\nFor information/Appointment: Tel: 041 4313 777 | WhatsApp: 03279640897', help_text='Footer text displayed at bottom of receipt')),
                ('receipt_logo', models.ImageField(blank=True, null=True, upload_to='printing/')),
                ('receipt_banner', models.ImageField(blank=True, null=True, upload_to='printing/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_type', models.CharField(choices=[('receipt', 'Receipt')], default='receipt', max_length=20)),
                ('yymm', models.CharField(db_index=True, max_length=4)),
                ('last_number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-yymm'],
                'indexes': [models.Index(fields=['seq_type', 'yymm'], name='reporting_p_seq_typ_e037c0_idx')],
                'unique_together': {('seq_type', 'yymm')},
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('findings_text', models.TextField(blank=True, null=True)),
                ('impression_text', models.TextField(blank=True, null=True)),
                ('limitations_text', models.TextField(blank=True, null=True)),
                ('narrative_version', models.CharField(default='v1', max_length=20)),
                ('narrative_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('service_visit_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_instance', to='workflow.servicevisititem')),
            ],
        ),
        migrations.CreateModel(
            name='ReportActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('verify', 'Verify'), ('return', 'Return for Correction'), ('publish', 'Publish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reporting.reportinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportInstanceV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values_json', models.JSONField(default=dict)),
                ('narrative_json', models.JSONField(blank=True, default=dict, help_text='Current narrative content (including overrides)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports_v2', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_instance_v2', to='workflow.servicevisititem')),
                ('template_v2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='reporting.reporttemplatev2')),
            ],
        ),
        migrations.CreateModel(
            name='ReportActionLogV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('save_draft', 'Draft Saved'), ('submit', 'Submit'), ('verify', 'Verify'), ('return', 'Return for Correction'), ('publish', 'Publish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reporting.reportinstancev2')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportParameterOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reporting.reportparameter')),
            ],
            options={
                'ordering': ['parameter', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code, e.g., USG_KUB', max_length=50)),
                ('name', models.CharField(help_text='Human readable name', max_length=150)),
                ('modality', models.CharField(help_text='Modality code, e.g., USG', max_length=20)),
                ('enable_narrative', models.BooleanField(default=True)),
                ('narrative_mode', models.CharField(choices=[('rule_based', 'Rule Based')], default='rule_based', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this template')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Template status', max_length=20)),
                ('is_frozen', models.BooleanField(default=False, help_text='If true, template cannot be edited')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When this version was activated', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When this version was archived', null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_profiles', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_profiles', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, help_text='Points to the original profile when cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='reporting.reportprofile')),
            ],
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='reporting.reportprofile'),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='reporting.reportprofile'),
        ),
        migrations.CreateModel(
            name='ReportProfileParameterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('overrides_json', models.JSONField(blank=True, help_text='Override defaults like normal_value, template, etc.', null=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.reportparameterlibraryitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_links', to='reporting.reportprofile')),
            ],
            options={
                'ordering': ['profile', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportPublishSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('findings_text', models.TextField()),
                ('impression_text', models.TextField(blank=True, default='')),
                ('limitations_text', models.TextField(blank=True, default='')),
                ('values_json', models.JSONField()),
                ('sha256', models.CharField(help_text='SHA256 hash of canonical content', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(upload_to='report_snapshots/%Y/%m/%d/')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_snapshots', to='reporting.reportinstance')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportPublishSnapshotV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values_json', models.JSONField(help_text='Immutable values at publish time')),
                ('narrative_json', models.JSONField(help_text='Generated narrative at publish time')),
                ('pdf_file', models.FileField(upload_to='report_snapshots_v2/%Y/%m/%d/')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 hash of template+values+narrative', max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_instance_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_snapshots_v2', to='reporting.reportinstancev2')),
                ('template_v2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='reporting.reporttemplatev2')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.reportparameter')),
                ('profile_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.reportprofileparameterlink')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reporting.reportinstance')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enforce_single_profile', models.BooleanField(default=True, help_text='If user must use this profile')),
                ('is_default', models.BooleanField(default=True, help_text='Auto-select this profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='reporting.reportprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_profiles', to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReportTemplateV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates_v2', to='catalog.service')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='reporting.reporttemplatev2')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('clone', 'Clone'), ('activate', 'Activate'), ('freeze', 'Freeze'), ('unfreeze', 'Unfreeze'), ('archive', 'Archive'), ('import', 'Import'), ('apply_baseline', 'Apply Baseline'), ('delete_blocked', 'Delete Blocked'), ('edit', 'Edit'), ('create', 'Create')], max_length=30)),
                ('entity_type', models.CharField(help_text='e.g., report_profile, report_parameter, service_profile', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportprofile',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_code_version'),
        ),
        migrations.AlterUniqueTogether(
            name='reportparameter',
            unique_together={('profile', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='reportprofileparameterlink',
            unique_together={('profile', 'library_item')},
        ),
        migrations.AlterUniqueTogether(
            name='reportpublishsnapshot',
            unique_together={('report', 'version')},
        ),
        migrations.AddIndex(
            model_name='reportpublishsnapshotv2',
            index=models.Index(fields=['report_instance_v2', 'published_at'], name='reporting_r_report__9d129f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportpublishsnapshotv2',
            index=models.Index(fields=['content_hash'], name='reporting_r_content_b9e133_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportpublishsnapshotv2',
            unique_together={('report_instance_v2', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='servicereportprofile',
            unique_together={('service', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='servicereporttemplatev2',
            unique_together={('service', 'template')},
        ),
    ]
