# Generated by Django 5.2.10 on 2026-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinstance',
            name='findings_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='impression_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='limitations_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='narrative_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportinstance',
            name='narrative_version',
            field=models.CharField(default='v1', max_length=20),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='join_label',
            field=models.CharField(blank=True, help_text="Join label for checklists, e.g. 'and'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='narrative_role',
            field=models.CharField(choices=[('finding', 'Finding'), ('impression_hint', 'Impression Hint'), ('limitation_hint', 'Limitation Hint'), ('ignore', 'Ignore')], default='finding', max_length=50),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='omit_if_values',
            field=models.JSONField(blank=True, help_text="List of values to omit sentence for, e.g. ['na', false]", null=True),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='sentence_template',
            field=models.TextField(blank=True, help_text='Template like: {name}: {value}{unit}.', null=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='enable_narrative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='narrative_mode',
            field=models.CharField(choices=[('rule_based', 'Rule Based')], default='rule_based', max_length=50),
        ),
    ]
