# Generated by Django 5.2.10 on 2026-01-26 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reportinstance_findings_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('verify', 'Verify'), ('return', 'Return for Correction'), ('publish', 'Publish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reporting.reportinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPublishSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('findings_text', models.TextField()),
                ('impression_text', models.TextField(blank=True, default='')),
                ('limitations_text', models.TextField(blank=True, default='')),
                ('values_json', models.JSONField()),
                ('sha256', models.CharField(help_text='SHA256 hash of canonical content', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(upload_to='report_snapshots/%Y/%m/%d/')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_snapshots', to='reporting.reportinstance')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('report', 'version')},
            },
        ),
    ]
