# Generated by Django 5.2.10 on 2026-01-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_reporttemplatereport"),
        ("templates", "0002_reporttemplate_reporttemplatefield_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplatereport",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="templates.reporttemplate",
            ),
        ),
    ]
