# Generated by Django 5.2.10 on 2026-01-28 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_reportactionlog_reportpublishsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingOrganizationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(help_text='Organization Name', max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_config/')),
                ('disclaimer_text', models.TextField(blank=True, default='This report is electronically verified.')),
                ('signatories_json', models.JSONField(blank=True, default=list, help_text='List of {name, designation}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportParameterLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(help_text='e.g. USG, XR, CT', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Unique identifier, e.g. liver_size', max_length=200, unique=True)),
                ('parameter_type', models.CharField(choices=[('number', 'Number'), ('dropdown', 'Dropdown'), ('checklist', 'Checklist'), ('boolean', 'Boolean'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('heading', 'Heading'), ('separator', 'Separator')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('default_normal_value', models.CharField(blank=True, max_length=500, null=True)),
                ('default_sentence_template', models.TextField(blank=True, null=True)),
                ('default_omit_if_values', models.JSONField(blank=True, null=True)),
                ('default_join_label', models.CharField(blank=True, max_length=50, null=True)),
                ('default_narrative_role', models.CharField(default='finding', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportProfileParameterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('overrides_json', models.JSONField(blank=True, help_text='Override defaults like normal_value, template, etc.', null=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporting.reportparameterlibraryitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_links', to='reporting.reportprofile')),
            ],
            options={
                'ordering': ['profile', 'order'],
                'unique_together': {('profile', 'library_item')},
            },
        ),
    ]
