# Generated by Django 5.2.10 on 2026-01-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportingorganizationconfig_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reportparameter',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier within profile', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reportparameterlibraryitem',
            name='default_options_json',
            field=models.JSONField(blank=True, help_text='List of {label, value} for dropdowns', null=True),
        ),
        migrations.AddField(
            model_name='reportvalue',
            name='profile_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.reportprofileparameterlink'),
        ),
        migrations.AddField(
            model_name='servicereportprofile',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Auto-select this profile'),
        ),
        migrations.AlterField(
            model_name='reportvalue',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reporting.reportparameter'),
        ),
    ]
