# Generated by Django 5.2.10 on 2026-01-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_reportvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportparameter',
            unique_together={('profile', 'slug')},
        ),
    ]
