# Generated by Django 4.2 on 2026-02-02
# Template Governance v1 Migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0006_alter_reportparameter_unique_together'),
    ]

    operations = [
        # Add versioning fields to ReportProfile
        migrations.AddField(
            model_name='reportprofile',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this template'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='revision_of',
            field=models.ForeignKey(blank=True, help_text='Points to the original profile when cloned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='reporting.reportprofile'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Template status', max_length=20),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='If true, template cannot be edited'),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When this version was activated', null=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this version was archived', null=True),
        ),
        migrations.AddField(
            model_name='reportprofile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_profiles', to=settings.AUTH_USER_MODEL),
        ),
        # Remove unique constraint on code to allow multiple versions
        migrations.AlterField(
            model_name='reportprofile',
            name='code',
            field=models.CharField(help_text='Unique code, e.g., USG_KUB', max_length=50),
        ),
        # Add unique together for (code, version)
        migrations.AddConstraint(
            model_name='reportprofile',
            constraint=models.UniqueConstraint(fields=['code', 'version'], name='unique_code_version'),
        ),
        # Create TemplateAuditLog model
        migrations.CreateModel(
            name='TemplateAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[
                    ('clone', 'Clone'),
                    ('activate', 'Activate'),
                    ('freeze', 'Freeze'),
                    ('unfreeze', 'Unfreeze'),
                    ('archive', 'Archive'),
                    ('import', 'Import'),
                    ('apply_baseline', 'Apply Baseline'),
                    ('delete_blocked', 'Delete Blocked'),
                    ('edit', 'Edit'),
                    ('create', 'Create'),
                ], max_length=30)),
                ('entity_type', models.CharField(help_text='e.g., report_profile, report_parameter, service_profile', max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the affected entity', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the action')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
