# Generated by Django 4.2 on 2026-02-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_service_default_price_turnaround_time"),
        ("workflow", "0012_receiptsnapshot_referring_consultant"),
        ("reporting", "0007_template_governance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(help_text="Unique code, e.g., USG_KUB_V2", max_length=50)),
                ("name", models.CharField(help_text="Human readable name", max_length=150)),
                ("modality", models.CharField(help_text="Modality code, e.g., USG", max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")], default="draft", max_length=20)),
                ("json_schema", models.JSONField(default=dict)),
                ("ui_schema", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceReportTemplateV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="report_templates_v2", to="catalog.service")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="service_links", to="reporting.reporttemplatev2")),
            ],
            options={
                "unique_together": {("service", "template")},
            },
        ),
        migrations.CreateModel(
            name="ReportInstanceV2",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("values_json", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("verified", "Verified"), ("returned", "Returned")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_reports_v2", to=settings.AUTH_USER_MODEL)),
                ("template_v2", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="instances", to="reporting.reporttemplatev2")),
                ("work_item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="report_instance_v2", to="workflow.servicevisititem")),
            ],
        ),
    ]
