# Generated by Django 5.2.10 on 2026-02-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_add_v2_publish_snapshot_and_narrative_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportpublishsnapshotv2',
            new_name='reporting_r_report__9d129f_idx',
            old_name='reporting_r_report__b8e9b5_idx',
        ),
        migrations.RenameIndex(
            model_name='reportpublishsnapshotv2',
            new_name='reporting_r_content_b9e133_idx',
            old_name='reporting_r_content_c0a1f7_idx',
        ),
    ]
