# Generated by Django 5.2.10 on 2026-02-03 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_rename_reporting_r_report__b8e9b5_idx_reporting_r_report__9d129f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplatev2',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='If true, template cannot be edited'),
        ),
        migrations.CreateModel(
            name='ReportActionLogV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('save_draft', 'Draft Saved'), ('submit', 'Submit'), ('verify', 'Verify'), ('return', 'Return for Correction'), ('publish', 'Publish')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_v2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='reporting.reportinstancev2')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
