# Generated by Django 5.2.10 on 2026-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_reporttemplatev2_is_frozen_reportactionlogv2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinstancev2',
            name='narrative_json',
            field=models.JSONField(blank=True, default=dict, help_text='Current narrative content (including overrides)'),
        ),
    ]
