# Generated by Django 5.2.10 on 2026-02-03 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_reportinstancev2_narrative_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBlockLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('block_type', models.CharField(choices=[('ui', 'UI Component'), ('narrative', 'Narrative Snippet')], default='ui', max_length=50)),
                ('content', models.JSONField(help_text='JSON schema/UI schema or narrative rule snippet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
