name: radreport
services:
  backend:
    build:
      context: /home/munaim/srv/apps/radreport/backend
      dockerfile: Dockerfile
    container_name: rims_backend_prod
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      CORS_ALLOWED_ORIGINS: https://rims.alshifalab.pk
      CSRF_TRUSTED_ORIGINS: https://rims.alshifalab.pk,https://api.rims.alshifalab.pk
      DB_ENGINE: postgresql
      DB_HOST: db
      DB_NAME: rims
      DB_PASSWORD: ""
      DB_PORT: "5432"
      DB_USER: rims
      DJANGO_ALLOWED_HOSTS: api.rims.alshifalab.pk,rims.alshifalab.pk,localhost,127.0.0.1
      DJANGO_DEBUG: "0"
      DJANGO_SECRET_KEY: ""
      GUNICORN_TIMEOUT: "120"
      GUNICORN_WORKERS: "4"
    networks:
      rims_network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 8000
        published: "8015"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: volume
        source: media_data
        target: /app/media
        volume: {}
      - type: volume
        source: static_data
        target: /app/staticfiles
        volume: {}
  db:
    container_name: rims_db_prod
    environment:
      POSTGRES_DB: rims
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: rims
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U rims
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:16-alpine
    networks:
      rims_network: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
  frontend:
    build:
      context: /home/munaim/srv/apps/radreport/frontend
      dockerfile: Dockerfile
    container_name: rims_frontend_prod
    networks:
      rims_network: null
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 80
        published: "8081"
        protocol: tcp
    restart: unless-stopped
networks:
  rims_network:
    name: radreport_rims_network
    driver: bridge
volumes:
  media_data:
    name: radreport_media_data
    driver: local
  postgres_data:
    name: radreport_postgres_data
    driver: local
  static_data:
    name: radreport_static_data
    driver: local
