# Generated by ChatGPT on 2026-01-18
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsgTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=True, help_text='Locked templates cannot be modified')),
                ('schema_json', models.JSONField(help_text='Full template schema including sections/fields/options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code', 'version'],
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UsgStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.TextField(blank=True, help_text='Reason why study is locked', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_usg_studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usg_studies', to='patients.patient')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_usg_studies', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='usg.usgtemplate')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_usg_studies', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(help_text='MUST link to patient registration/visit in RIMS', on_delete=django.db.models.deletion.PROTECT, related_name='usg_studies', to='studies.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsgServiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('hidden_sections', models.JSONField(blank=True, default=list, help_text='Array of section keys to hide for this service')),
                ('forced_na_fields', models.JSONField(blank=True, default=list, help_text='Array of field keys that should be marked as NA by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_profiles', to='usg.usgtemplate')),
            ],
            options={
                'ordering': ['service_code'],
            },
        ),
        migrations.CreateModel(
            name='UsgPublishedSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(db_index=True, max_length=100)),
                ('template_version', models.PositiveIntegerField()),
                ('renderer_version', models.CharField(default='usg_renderer_v1', help_text='Version of renderer used to generate narrative', max_length=50)),
                ('published_json_snapshot', models.JSONField(help_text='Frozen copy of all field_key → {value, is_na}')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen copy of template schema at publish time')),
                ('published_text_snapshot', models.TextField(help_text='Final narrative text as issued')),
                ('pdf_file_path', models.CharField(blank=True, help_text='Local filesystem path to the PDF stored under MEDIA_ROOT', max_length=500, null=True)),
                ('pdf_drive_file_id', models.CharField(blank=True, help_text='Google Drive file ID for the PDF', max_length=255, null=True)),
                ('pdf_drive_folder_id', models.CharField(blank=True, help_text='Google Drive folder ID where PDF is stored', max_length=255, null=True)),
                ('pdf_sha256', models.CharField(blank=True, help_text='SHA256 hash of PDF bytes for integrity', max_length=64, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('audit_note', models.TextField(blank=True, help_text='Audit trail notes (e.g., PDF regeneration)', null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshot', to='usg.usgstudy')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UsgFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(db_index=True, max_length=200)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('is_not_applicable', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='usg.usgstudy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['field_key'],
                'unique_together': {('study', 'field_key')},
            },
        ),
        migrations.AddIndex(
            model_name='usgtemplate',
            index=models.Index(fields=['code', 'version'], name='usg_usgtem_code_46b7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='usgtemplate',
            index=models.Index(fields=['category'], name='usg_usgtem_catego_eb7b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='usgserviceprofile',
            index=models.Index(fields=['service_code'], name='usg_usgser_servic_21a80c_idx'),
        ),
        migrations.AddIndex(
            model_name='usgstudy',
            index=models.Index(fields=['patient'], name='usg_usgstu_patien_8f24e1_idx'),
        ),
        migrations.AddIndex(
            model_name='usgstudy',
            index=models.Index(fields=['visit'], name='usg_usgstu_visit__0e51a1_idx'),
        ),
        migrations.AddIndex(
            model_name='usgstudy',
            index=models.Index(fields=['status'], name='usg_usgstu_status_1d911e_idx'),
        ),
        migrations.AddIndex(
            model_name='usgstudy',
            index=models.Index(fields=['service_code'], name='usg_usgstu_servic_6b2f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='usgfieldvalue',
            index=models.Index(fields=['study', 'field_key'], name='usg_usgfie_study__b1d291_idx'),
        ),
        migrations.AddIndex(
            model_name='usgfieldvalue',
            index=models.Index(fields=['is_not_applicable'], name='usg_usgfie_is_not_273fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='usgpublishedsnapshot',
            index=models.Index(fields=['study'], name='usg_usgpub_study__e6cc32_idx'),
        ),
        migrations.AddIndex(
            model_name='usgpublishedsnapshot',
            index=models.Index(fields=['template_code'], name='usg_usgpub_template_6f9b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='usgpublishedsnapshot',
            index=models.Index(fields=['pdf_drive_file_id'], name='usg_usgpub_pdf_dri_4d4c6d_idx'),
        ),
    ]
