# Generated by Django 5.2.10 on 2026-01-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usg', '0002_rename_usg_usgfie_study__b1d291_idx_usg_usgfiel_study_i_acf6f5_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='usgfieldvalue',
                    new_name='usg_usgfiel_study_i_acf6f5_idx',
                    old_name='usg_usgfie_study__b1d291_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgfieldvalue',
                    new_name='usg_usgfiel_is_not__d228b4_idx',
                    old_name='usg_usgfie_is_not_273fb5_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgpublishedsnapshot',
                    new_name='usg_usgpubl_study_i_b7756a_idx',
                    old_name='usg_usgpub_study__e6cc32_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgpublishedsnapshot',
                    new_name='usg_usgpubl_templat_28535c_idx',
                    old_name='usg_usgpub_template_6f9b1d_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgpublishedsnapshot',
                    new_name='usg_usgpubl_pdf_dri_bfa86d_idx',
                    old_name='usg_usgpub_pdf_dri_4d4c6d_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgserviceprofile',
                    new_name='usg_usgserv_service_46a7e9_idx',
                    old_name='usg_usgser_servic_21a80c_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgstudy',
                    new_name='usg_usgstud_patient_e85b3c_idx',
                    old_name='usg_usgstu_patien_8f24e1_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgstudy',
                    new_name='usg_usgstud_visit_i_f94007_idx',
                    old_name='usg_usgstu_visit__0e51a1_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgstudy',
                    new_name='usg_usgstud_status_9d3aeb_idx',
                    old_name='usg_usgstu_status_1d911e_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgstudy',
                    new_name='usg_usgstud_service_ae1e13_idx',
                    old_name='usg_usgstu_servic_6b2f8b_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgtemplate',
                    new_name='usg_usgtemp_code_1c5f0d_idx',
                    old_name='usg_usgtem_code_46b7e6_idx',
                ),
                migrations.RenameIndex(
                    model_name='usgtemplate',
                    new_name='usg_usgtemp_categor_7fe72d_idx',
                    old_name='usg_usgtem_catego_eb7b3d_idx',
                ),
            ]
        ),
        migrations.AddField(
            model_name='usgstudy',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the template schema at the time of report creation', null=True),
        ),
    ]
