# Generated by Django 5.2.10 on 2026-02-04 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
        ('patients', '0004_rename_patients_pa_patient_idx_patients_pa_patient_42dea5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indication', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.service')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('insurance', 'Insurance'), ('other', 'Other')], default='', max_length=20)),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('receipt_pdf_path', models.CharField(blank=True, default='', max_length=500)),
                ('receipt_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=30, unique=True)),
                ('indication', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('final', 'Final'), ('delivered', 'Delivered')], default='registered', max_length=20)),
                ('performed_by', models.CharField(blank=True, default='', max_length=120)),
                ('reported_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='studies.orderitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='catalog.service')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studies', to='studies.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='studies.visit'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_number'], name='studies_vis_visit_n_81c1af_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient'], name='studies_vis_patient_84cc87_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['is_finalized'], name='studies_vis_is_fina_8a6004_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['receipt_number'], name='studies_vis_receipt_6d9a51_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['accession'], name='studies_stu_accessi_bd6149_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['status'], name='studies_stu_status_34eaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['visit'], name='studies_stu_visit_i_a8e1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['visit'], name='studies_ord_visit_i_bd04a7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['service'], name='studies_ord_service_a7c029_idx'),
        ),
    ]
