# Generated by Django 5.2.9 on 2026-01-06 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=30, unique=True)),
                ('indication', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('final', 'Final'), ('delivered', 'Delivered')], default='registered', max_length=20)),
                ('performed_by', models.CharField(blank=True, default='', max_length=120)),
                ('reported_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='patients.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studies', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accession'], name='studies_stu_accessi_bd6149_idx'), models.Index(fields=['status'], name='studies_stu_status_34eaf0_idx')],
            },
        ),
    ]
