# Generated by Django 5.2.9 on 2026-01-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date_of_birth_alter_patient_mrn'),
        ('studies', '0002_orderitem_study_order_item_visit_orderitem_visit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(db_index=True, max_length=4, unique=True)),
                ('last_number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-yymm'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(default='Consultants Clinic Place', max_length=200)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt Settings',
                'verbose_name_plural': 'Receipt Settings',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='receipt_pdf_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['receipt_number'], name='studies_vis_receipt_6d9a51_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptsequence',
            index=models.Index(fields=['yymm'], name='studies_rec_yymm_1ee1a9_idx'),
        ),
        migrations.AddField(
            model_name='receiptsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
