# Generated by Django 5.2.9 on 2026-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_receiptsequence_receiptsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='footer_text',
            field=models.TextField(blank=True, default='', help_text='Footer text displayed at bottom of receipt'),
        ),
    ]
