# Generated by Django 5.2.10 on 2026-01-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_backfill_receipt_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsettings',
            name='footer_text',
            field=models.TextField(blank=True, default='Adjacent Excel Labs, Near Arman Pan Shop Faisalabad Road Jaranwala\nFor information/Appointment: Tel: 041 4313 777 | WhatsApp: 03279640897', help_text='Footer text displayed at bottom of receipt'),
        ),
        migrations.AlterField(
            model_name='receiptsettings',
            name='header_text',
            field=models.CharField(default='Consultant Place Clinic', max_length=200),
        ),
    ]
