# Generated by Django (manual for apps.printing)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReceiptBrandingConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("receipt_header_text", models.TextField(default="Consultant Place Clinic")),
                ("receipt_footer_text", models.TextField(blank=True, default="")),
                ("receipt_logo", models.ImageField(blank=True, null=True, upload_to="printing/receipt/")),
                ("receipt_banner", models.ImageField(blank=True, null=True, upload_to="printing/receipt/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Receipt Branding",
                "verbose_name_plural": "Receipt Branding",
            },
        ),
    ]
