# Generated by Django 5.2.9 on 2026-01-06 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tat_minutes', models.PositiveIntegerField(default=60)),
                ('requires_radiologist_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.modality')),
            ],
            options={
                'unique_together': {('modality', 'name')},
            },
        ),
    ]
