# Generated by Django 5.2.9 on 2026-01-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Radiology', 'Radiology'), ('Lab', 'Lab'), ('OPD', 'OPD'), ('Procedure', 'Procedure')], default='Radiology', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alias for price, CSV-driven', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tat_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='tat_value',
            field=models.PositiveIntegerField(default=1, help_text='TAT numeric value'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tat_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Calculated TAT in minutes'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['code'], name='catalog_ser_code_fc9a02_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='catalog_ser_categor_872480_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='catalog_ser_is_acti_43a295_idx'),
        ),
    ]
