# Generated by Django 5.2.10 on 2026-01-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='default_template',
        ),
    ]
