# Generated by Django 5.2.9 on 2026-01-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
