# Generated by Django 5.2.10 on 2026-01-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patient_reg_no'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_patient_42dea5_idx',
            old_name='patients_pa_patient_idx',
        ),
    ]
