# Generated by Django 5.2.10 on 2026-01-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
        ('consultants', '0001_initial'),
        ('workflow', '0007_receipt_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['name'], 'verbose_name': 'Service Catalog (Deprecated)', 'verbose_name_plural': 'Service Catalogs (Deprecated)'},
        ),
        migrations.RenameIndex(
            model_name='receiptsnapshot',
            new_name='workflow_re_receipt_4cc9dc_idx',
            old_name='workflow_re_receipt_4ee260_idx',
        ),
        migrations.RenameIndex(
            model_name='receiptsnapshot',
            new_name='workflow_re_issued__09393e_idx',
            old_name='workflow_re_issued__922eff_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecatalog',
            new_name='workflow_se_code_ecae7f_idx',
            old_name='workflow_se_code_idx',
        ),
        migrations.RenameIndex(
            model_name='servicecatalog',
            new_name='workflow_se_is_acti_671950_idx',
            old_name='workflow_se_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisit',
            new_name='workflow_se_visit_i_5a45ab_idx',
            old_name='workflow_se_visit_i_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisit',
            new_name='workflow_se_status_d579c2_idx',
            old_name='workflow_se_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisit',
            new_name='workflow_se_patient_fa4016_idx',
            old_name='workflow_se_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisit',
            new_name='workflow_se_service_8810be_idx',
            old_name='workflow_se_service_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisit',
            new_name='workflow_se_registe_da8add_idx',
            old_name='workflow_se_registe_idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisititem',
            new_name='workflow_se_service_e669a3_idx',
            old_name='workflow_se_service__idx',
        ),
        migrations.RenameIndex(
            model_name='servicevisititem',
            new_name='workflow_se_service_779aee_idx',
            old_name='workflow_se_service_2_idx',
        ),
        migrations.RenameIndex(
            model_name='statusauditlog',
            new_name='workflow_st_service_a769ab_idx',
            old_name='workflow_st_service_idx',
        ),
        migrations.RenameIndex(
            model_name='statusauditlog',
            new_name='workflow_st_changed_59932b_idx',
            old_name='workflow_st_changed_idx',
        ),
        migrations.RenameIndex(
            model_name='usgreport',
            new_name='workflow_us_report__96c62d_idx',
            old_name='workflow_us_report_s_idx',
        ),
        migrations.RenameIndex(
            model_name='usgreport',
            new_name='workflow_us_version_86a0ba_idx',
            old_name='workflow_us_version_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount still due after payments', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount (fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alias for total_amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal - discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='statusauditlog',
            name='from_status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending Verification'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='statusauditlog',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Required when RETURNED', null=True),
        ),
        migrations.AlterField(
            model_name='statusauditlog',
            name='to_status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('PENDING_VERIFICATION', 'Pending Verification'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usgreport',
            name='report_json',
            field=models.JSONField(default=dict, help_text='Legacy structured report data - use canonical fields instead'),
        ),
        migrations.AddIndex(
            model_name='servicevisititem',
            index=models.Index(fields=['status'], name='workflow_se_status_d280c6_idx'),
        ),
    ]
