# Generated by Django 5.2.10 on 2026-01-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_alter_servicecatalog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usgreport',
            name='scan_quality',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Limited', 'Limited'), ('Not recorded', 'Not recorded')], default='', help_text='Good/Fair/Limited - REQUIRED before FINAL', max_length=20),
        ),
    ]
