# Generated by Django 5.2.10 on 2026-01-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_usgreport_scan_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usgreport',
            name='template_version',
        ),
    ]
