# Generated by Django 5.2.10 on 2026-01-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_alter_usgreport_scan_quality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USGReport',
        ),
    ]
