# Generated by Django 5.2.10 on 2026-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_delete_usgreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='referring_consultant',
            field=models.CharField(blank=True, default='', help_text='Text field for referring consultant name', max_length=150),
        ),
    ]
