# Generated by Django 5.2.10 on 2026-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_servicevisit_referring_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsnapshot',
            name='referring_consultant',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
