# Generated by Django 5.2.10 on 2026-01-16 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_service_default_price_turnaround_time"),
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=80)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short Text"),
                            ("long_text", "Long Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("heading", "Heading"),
                            ("separator", "Separator"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, default="", max_length=300)),
                ("default_value", models.JSONField(blank=True, null=True)),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("validation", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="templates.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("template", "key")},
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateFieldOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=120)),
                ("label", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="templates.reporttemplatefield",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="catalog.service",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="templates.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "created_at"],
                "unique_together": {("service", "template")},
            },
        ),
    ]
