# Generated by Django 5.2.10 on 2026-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_template_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplatefield',
            name='na_allowed',
            field=models.BooleanField(default=False, help_text="Allow 'Not Applicable' option for this field"),
        ),
    ]
