# Generated by Django 5.1.6 on 2026-02-11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by", models.CharField(default="system", max_length=150)),
                ("trigger", models.CharField(db_index=True, default="manual", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("SUCCESS", "Success"), ("FAILED", "Failed")],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("BACKUP", "Backup"),
                            ("RESTORE", "Restore"),
                            ("UPLOAD", "Upload"),
                            ("IMPORT", "Import"),
                            ("DELETE", "Delete"),
                            ("TEST_CLOUD", "Test Cloud"),
                        ],
                        default="BACKUP",
                        max_length=24,
                    ),
                ),
                ("backup_path", models.CharField(blank=True, default="", max_length=512)),
                ("db_path", models.CharField(blank=True, default="", max_length=512)),
                ("media_path", models.CharField(blank=True, default="", max_length=512)),
                ("infra_path", models.CharField(blank=True, default="", max_length=512)),
                ("logs_path", models.CharField(blank=True, default="", max_length=512)),
                ("meta_path", models.CharField(blank=True, default="", max_length=512)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("is_deletable", models.BooleanField(default=False)),
                ("uploaded", models.BooleanField(default=False)),
                ("upload_remote", models.CharField(blank=True, default="", max_length=255)),
                ("upload_log_path", models.CharField(blank=True, default="", max_length=512)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
