# Generated by Django 5.2.10 on 2026-01-17 21:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflow", "0006_migrate_service_catalog_to_catalog_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultant_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantBillingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("PERCENT_SPLIT", "Percent Split")],
                        default="PERCENT_SPLIT",
                        max_length=50,
                    ),
                ),
                (
                    "consultant_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("active_from", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_rules",
                        to="consultants.consultantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-active_from", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "gross_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "net_payable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "clinic_share",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINALIZED", "Finalized"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="consultants.consultantprofile",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_consultant_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultantSettlementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_amount_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "paid_amount_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "consultant_share_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "clinic_share_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultant_settlement_lines",
                        to="workflow.servicevisititem",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="consultants.consultantsettlement",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(
                fields=["display_name"], name="consultants_display_55b054_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantprofile",
            index=models.Index(
                fields=["is_active"], name="consultants_is_acti_907c21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantbillingrule",
            index=models.Index(
                fields=["consultant", "is_active"],
                name="consultants_consult_8ff139_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultantsettlement",
            index=models.Index(
                fields=["consultant", "status"], name="consultants_consult_32679d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantsettlement",
            index=models.Index(
                fields=["date_from", "date_to"], name="consultants_date_fr_50387e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantsettlementline",
            index=models.Index(
                fields=["settlement"], name="consultants_settlem_953fe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultantsettlementline",
            index=models.Index(
                fields=["service_item"], name="consultants_service_55f420_idx"
            ),
        ),
    ]
