# Generated by Django 5.2.10 on 2026-01-19 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_default_price_turnaround_time'),
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantbillingrule',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Specific service override. If blank, applies to all services not otherwise specified.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_billing_rules', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='degrees',
            field=models.CharField(blank=True, default='', help_text='e.g. MBBS, FCPS', max_length=200),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='e.g. Consultant Radiologist', max_length=100),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
