# Generated by Django 5.0.14 on 2026-01-21 10:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_consultantbillingrule_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantbillingrule',
            name='consultant_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='consultantbillingrule',
            name='consultant_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='consultantbillingrule',
            name='rule_type',
            field=models.CharField(choices=[('PERCENT_SPLIT', 'Percent Split'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENT_SPLIT', max_length=50),
        ),
    ]
