# Generated by Django (manual for apps.sequences)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50)),
                ("period", models.CharField(max_length=16)),
                ("value", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="sequencecounter",
            constraint=models.UniqueConstraint(fields=("key", "period"), name="unique_seq_key_period"),
        ),
        migrations.AddIndex(
            model_name="sequencecounter",
            index=models.Index(fields=["key", "period"], name="sequences_sequence_key_period_idx"),
        ),
    ]
