# Generated by Django 5.2.11 on 2026-02-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sequencecounter',
            new_name='sequences_s_key_1cddf9_idx',
            old_name='sequences_sequence_key_period_idx',
        ),
    ]
